[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "https://www.lucasmachado.io/*"
  to = "https://lucasmachado.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.lucasmachado.com/*"
  to = "https://lucasmachado.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://lucasmachado.com.br/*"
  to = "https://lucasmachado.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://lucasmachado1.netlify.com/*"
  to = "https://lucasmachado.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/posts/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/agora"
  to = "/"
  status = 301

[[redirects]]
  from = "/agora/"
  to = "/"
  status = 301

[[redirects]]
  from = "/sobre"
  to = "/"
  status = 301

[[redirects]]
  from = "/sobre/"
  to = "/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
