[build]
publish = "public"
command = "hugo --gc --minify --baseURL $URL"

[context.production.environment]
HUGO_VERSION = "0.127.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "https://www.lucasmachado.com/*"
to = "https://lucasmachado.io/:splat"
status = 301
force = true

[[redirects]]
from = "https://lucasmachado.com.br/*"
to = "https://lucasmachado.io/:splat"
status = 301
force = true

[[redirects]]
from = "https://lucasmachado1.netlify.com/*"
to = "https://lucasmachado.io/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/404.html"
status = 404